### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by devonwhalen** [WillHayCode/Deadname-Remover#1]
Hi! I love your program, it's extremely helpful (especially for email). I was wondering if there was any way to have the program check if the last name matches the user's last name before replacing the deadname? As it is right now, every instance of my deadname gets replaced with my name, not just the ones referring to me. Would love to see a feature preventing this, as I have a massively popular deadname.

**Comment by WilliamHayward** [comment]
This is a great idea, I'll look into adding an option to only replace the name if a last name is present.

**Comment by cgpelletier** [comment]
Hey another cool feature would be to be able to change friend's deadnames too. Like I was sending money through paypal to my girlfriend and It'd be nice to be able to change her name to her preferred name too.

**Comment by AsherDoodles** [comment]
The option to be able to quickly switch the replacer on and off could be useful to people too, for example, if you have a common first name and don't need it on while you're, say, reading a story online and having them suddenly have a new name (This happened to me and I was sitting there for nearly a full minute wondering why Jade Harley was suddenly Asher Harley) Or maybe for people who aren't out yet and don't want it displaying if there are other people in the room

**Comment by WillHayCode** [comment]
I'm back to working on this, gonna add some configurable options like this
