### ISSUE TITLE
feature request: replacing content after site is loaded

### ISSUE THREAD

**Issue by timeflow-x** [WillHayCode/Deadname-Remover#103]
first off I just wanted to say that I really really appreciate this browser extension since it really helps me.

however, after I load a page, my deadname still sometimes appears in them in for example google drive or some other webpage that updates itself frequently. is it possible to add a feature where the extension can replace deadnames after the page is loaded too? I think it would be really helpful

once again thanks for making this

**Comment by Gusted** [comment]
Update to latest version.
