### ISSUE TITLE
Suggesting a feature

### ISSUE THREAD

**Issue by phonymichael** [WillHayCode/Deadname-Remover#110]
Dear Developers,
i cant begin to say how much i appreciate this feature! I do however have a suggestion. I think it would be great if we could enter multiple deadnames... i have dead nicknames that most of my teachers call me but my google classroom calls me by my full deadname. i have it set to my full deadname but it would be great to be able to also replace my dead nicknames. 
Thank you! -Michael

**Comment by AnnoyedCat** [comment]
i have the same issue :( i hate my nicknames and I also want to add my triggers so they just appear as something else on screen
