### ISSUE TITLE
Google Meet

### ISSUE THREAD

**Issue by dbaush** [WillHayCode/Deadname-Remover#118]
The extension does not remove the deadname from displaying on Google Meet for other users. On my end, I can see the name change, but for those on the call with me, the deadname remains on their end.

**Comment by RetroAsgardian** [comment]
That's because the extension can't actually change the name registered in your systems, it can only edit the text that is displayed on your end. (The only way it could change your name for other users would be to hack Google, which is very difficult and also illegal.)

**Comment by Gusted** [comment]
> On my end, I can see the name change, but for those on the call with me, the deadname remains on their end.

That's the purpose of this extension and also changing for other people is impossible.
