### ISSUE TITLE
dead-nickname remover

### ISSUE THREAD

**Issue by The-Morrigan** [WillHayCode/Deadname-Remover#12]
maybe add fields for any nicknames one used to go by and may want removed, and what they want to see instead? for example, say someone's deadname is Elizabeth, and the extension removes that, but someone could still call them Liz and the program, in its current form, wouldn't change it.

**Comment by WillHayCode** [comment]
Great suggestion! This should be in the next update, barring something catastrophic happening

**Comment by The-Morrigan** [comment]
awesome! I look forward to seeing it!
