### ISSUE TITLE
Deadnames that are words or parts of words become the prefered name, even if you don't want them to

### ISSUE THREAD

**Issue by VinniSauce** [WillHayCode/Deadname-Remover#133]
My deadname last name is mix, so in things like "Remix" or "Mixed" it becomes "ReSabio" or "Sabioed"

Another issue, when this happens, the text stays there even if the thing that was there before changes

Say someone uploads a remix to youtube, whenever that shows up in my recommended, every video in that spot from the on will have the title of the remix.

**Comment by Gusted** [comment]
Is fixed in the latest update.
