### ISSUE TITLE
Change the icon of the deadname remover

### ISSUE THREAD

**Issue by Mango-mangoes** [WillHayCode/Deadname-Remover#141]
Hi! i am a user in this extension and is not a issue but a request, it will be great to have a option to change the flag to a base color, i think it would be more discrete for the persons who share pcs with another people. Thanks for reading and i hope is implemented

**Comment by geard-dev** [comment]
Hey @Mango-mangoes ! I think this is a great idea, even though I'm not an official developer, I'll see if I can work on it in a fork
