### ISSUE TITLE
Suggestion: Option to only change name when surrounded by spaces

### ISSUE THREAD

**Issue by Richard-Conway** [WillHayCode/Deadname-Remover#15]
Say my name is Samantha, and my deadname is Tom. If I see the word Tomorrow, it'll turn into Samanthaorrow. Which is weird, and hopefully not too hard to fix, by just changing it so the script isn't looking for "Tom" it's looking for " Tom ".

**Comment by WillHayCode** [comment]
This fix will be in the next update
