### ISSUE TITLE
Font Color Change

### ISSUE THREAD

**Issue by EmilyLove26** [WillHayCode/Deadname-Remover#160]
So I just accidentally outed myself to someone I wasn't already out to because I forgot I installed this app and logged into one of my deadname accounts. I thought they somehow figured it out when they called me Emily, but no it was the extension doing it's job. Would it be possible to change the color of the replaced text to serve as a visual indicator that the extension replaced my deadname. I realize this is completely my fault and it slipped my mind, but a visual reminder would have certainly been nice :)

Anyways, have a great day and thank you for this extension

**Comment by AriGibson** [comment]
Ooo, that's a cool idea! I might give it a shot when I find some time later 😊

**Comment by EmilyLove26** [comment]
Woo! Tysm

**Comment by EmilyLove26** [comment]
Built and tested. This is nice. Hopefully in a future release, we can change the color.
