### ISSUE TITLE
Maybe a way to input multiple deadnames?

### ISSUE THREAD

**Issue by lunwyr** [WillHayCode/Deadname-Remover#167]
I appreciate this tool a lot! I just think it would be cool to be able to put in multiple deadnames so you can avoid certain nicknames and stuff in addition to the one name you can already input

thank you for your time and your great work on the app!

**Comment by Gusted** [comment]
Hi @lunwyr!

Please update to the latest version that has this feature, make sure to fill out a dead name already to make the arrow visible
![](https://i.imgur.com/hNg0Eix.png)
