### ISSUE TITLE
Deadname-Remover doesn't change my last name

### ISSUE THREAD

**Issue by edemonaz** [WillHayCode/Deadname-Remover#168]
Hello,
I have an issue with Deadname-Remover. It changes my first name just fine and it's helped a lot, but it doesn't do the same for my last name. I don't know if this is because it doesn't actually change last names at all or because I did something wrong. I understand that since most of the people who use this have the same last name in their old and preferred name, you wouldn't need to change it, but I live in a country where there are feminine and masculine versions of last names, and seeing my old last name makes me really dysphoric. Maybe it's an issue on my side but I don't know what I might've done wrong.

**Comment by Gusted** [comment]
Hi @edemonaz!

Did you make sure you have the correct settings? E.g. No typo's.

Regards,
Gusted

**Comment by edemonaz** [comment]
Hi,
Thanks for answering. I don't know what counts as a typo but my name contains the letter "ř" and "á" so if the program is only set for the English alphabet, it might have been the problem.

**Comment by Gusted** [comment]
@WillHayCode Any Idea why `\b` doesn't work with non English words?
So far I see it doesn't really seems to work alongside each other?
