### ISSUE TITLE
Sometimes it removes stuff that shouldnt be removed

### ISSUE THREAD

**Issue by Estall77** [WillHayCode/Deadname-Remover#21]
My deadname is Ed, so whenever theres a past tense verb or even a word as common as red it changes to activatEve, subscribEve, attachEve. rEve, maybe have it case sensitive, since names would typically begin with a capital whereas a normal word with my deadname in wouldn't

**Comment by Ivan-Johnson** [comment]
Confirmed in 1.0.0 using Chromium "Version 83.0.4103.61 (Official Build) Arch Linux (64-bit)".

That being said, this seems to be a duplicate of issue #2, which is fixed as part of the version 1.2 milestone.

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
