### ISSUE TITLE
DNR Privacy Policy

### ISSUE THREAD

**Issue by WillHayCode** [WillHayCode/Deadname-Remover#246]
This week I received the following email

> We have a student requesting our school district allow your Chrome extension Deadname Remover. We need a privacy policy that is CIPA and FERPA compliant in order to do so. Can you provide that?

Getting the plugin into the hands of more schools would be a big win - I'm not familiar with CIPA/FERPA, so if anyone can offer advice or guidance that would be appreciated, else I'll look into it after I've set up group publishing this weekend.

**Comment by Gusted** [comment]
Hi @WillHayCode!

Credits to the school for reaching out!

So my 2 cents on my legal experience and disclamer. I'm not a lawyer.

So first of CIPA and FERPA have both in common the `privacy` aspect. Whereby `CIPA` is applicable to `Online protection` and FERPA to focus on how schools go around with disclosing information of a student.

Luckily creating a CIPA and FERPA compliant privacy policy for an open-source extension that doesn't collect data is fairly simple, with the exception that we use browser's webAPI `chrome.storage.sync` which need a special disclosure under `Third Party`.

So something like
```
### Personal data

Deadname-Remover had never collected and will never collect any personal data, browsing history etc.

### Third Party
Deadname-Remover uses Chrome (Chromium) or WebExtensions Storage Sync API for storing user's settings.
```

Alternatively we can make an option to switch between `chrome.storage.sync` and `chrome.storage.local` if the school want a water-proof CIPA compliant, however it's third party and both storage are considered safe. I will draft up a PR with a good Privacy Policy that can be used and are CIPA and FERPA compliant.
