### ISSUE TITLE
Typed out Names

### ISSUE THREAD

**Issue by veryduck-somanyduck** [WillHayCode/Deadname-Remover#28]
When i type out my dead name it automatically changes it to my name which is generally not a terrible problem but in times when i /need/ to type my dead name like on forms or in the case that some one else has the same name i need to turn off the feature and turn it back on again which is sometimes more dysphoric than just using my deadname.

instead maybe there could be an option where you can toggle it on and off or you can choose whether you want it to autocorrect when you type it out or not. thanks so much for listening !

Gregory Ballard

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
