### ISSUE TITLE
Replace multiple spellings

### ISSUE THREAD

**Issue by Amoo0001** [WillHayCode/Deadname-Remover#300]
Hi,

My dead family name has two spellings (one with spaces and one bunched together without spaces), and some sites use one spelling (with the spaces) while others use the other spelling (with all the letters smushed together).

Could you add an option to convert more names?  If you had First, Middle, Last, Other, then I could use Last for one spelling and Other for the other spelling of my dead family name.

I never use GitHub anymore and will not see a reply, but thanks for reading and for making this extension <3

**Comment by AriGibson** [comment]
Hope you do get this @Amoo0001 , check #234!

**Comment by Amoo0001** [comment]
That was a fast reply!  You caught me before I signed out :)  Thank you so much, I didn't see those arrows!!
