### ISSUE TITLE
Recursive infinite renaming

### ISSUE THREAD

**Issue by aopom** [WillHayCode/Deadname-Remover#37]
Hello, first thanks for this great extension.

If someone has the deadname Jean and her name is Jeanne, the extension will replace Jean with Jean**ne**, then Jeanne with Jean**ne**ne, then Jean**ne**nene, etc... And it shortly fills all the page ^^

Maybe the extension should check if the deadname match doesn't also matches the name.
It could also escape the deadname with <>, example: **\\<Jean\\>** should match **Jean is nice**, **Jean, you know...** but not **Jeanne, are u ok ?**

**Comment by aopom** [comment]
Another issue is related to that one: #65

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
