### ISSUE TITLE
Extension occasionaly opens options page by itself

### ISSUE THREAD

**Issue by Enbika** [WillHayCode/Deadname-Remover#4]
@Enbika:
> Not sure if this is an issue with the Chrome version as well, but the options page occasionally opens by itself when opening the browser, even though the options are already set.

@WillHayCode:
> Yeah that happens on the Chrome version as well sometimes, for some reason. If anyone ever finds out why that would be pretty 10/10.

(moved from Enbika#1)

**Comment by WillHayCode** [comment]
Thanks for transferring the issue across! One of the planned changes is moving the options to a pop up dialog, which should hopefully also fix this up

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
