### ISSUE TITLE
Spelling corrections/ elongating a name

### ISSUE THREAD

**Issue by kitsukamo** [WillHayCode/Deadname-Remover#44]
Hi there, My friend recently discovered this for there own use, and i being curious wanted to test it out for my self. My Name is Georges, which you might notice has an s at the end, its silent so it oft gets forgotten in correspondence. Interested in using your software for that purpose i tried to have Georges replaced with Georges. Ngl it was beautiful to watch the google results fill with "sssssssssssssssssssssssssssssssssssssssssss" when the software registered the "George" inside of Georges and replaced it repeatedly. I realize my desire is not really in the scope of your product base, but if someone wanted to change from Dan to Daniella I think they would run into the same problem. An idea might be to somehow frame the dead-name, so if it registered as part of another word it wouldn't be flagged and replaced.
This is an awesome extension I wish you guys the best of luck

**Comment by kitsukamo** [comment]
![image](https://user-images.githubusercontent.com/69814736/90428057-6eae0700-e091-11ea-845d-94cea67c1a4d.png)

**Comment by aopom** [comment]
Oh, I opened an issue that is the same as this one: #37. It's also related to this one #65

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
