### ISSUE TITLE
[Suggestion] Ability to disable extension for certain websites

### ISSUE THREAD

**Issue by EvilDeaaaadd** [WillHayCode/Deadname-Remover#5]
For some reason this extension slows some websites down a lot. I really like using this extension, so I can't really disable it fully. I think it would be useful if there was an option to whitelist/blacklist some websites.

**Comment by xhardlynormal** [comment]
Came here to write just this. I don't have to deal with deadname on Discord or Twitter, but having this there changes my friends name as well...

**Comment by WillHayCode** [comment]
Pausing is definitely on the cards for the next update! I've been looking into the slowdown (it happens for me too, on seemingly random websites) so hopefully that will be looked at soon, but yeah pausing is for in the next update

**Comment by WillHayCode** [comment]
This should be resolved with the newest update (1.2) - there's been massive optimization and you can now disable the app in its settings
