### ISSUE TITLE
Maybe bug report?

### ISSUE THREAD

**Issue by A01376720** [WillHayCode/Deadname-Remover#56]
Hi, your extension is hella cool so thanks firstly!

Also I think I may have stumbled upon a bug. I put my name in the options and everything and saved them, I then go to pages where my name appears and funny enough the last letter of my first name keeps appearing infinitely. At first I thought I had written something wrong in the options, like an extra space or something, but now I know it's most probably not that.

So I thought I should tell you : D

![imagen](https://user-images.githubusercontent.com/61218550/90569674-e7858f80-e173-11ea-89af-9abe7116f9b6.png)
![imagen](https://user-images.githubusercontent.com/61218550/90569793-1865c480-e174-11ea-94c0-c7c5fce848e1.png)
![imagen](https://user-images.githubusercontent.com/61218550/90569929-5fec5080-e174-11ea-9af6-a6906d705325.png)

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
