### ISSUE TITLE
[Suggestion] Additional Names

### ISSUE THREAD

**Issue by beegif** [WillHayCode/Deadname-Remover#6]
This extension has been amazing for me but I see both my full name and a shortened version pretty often. I've tried messing with it a bit but can't seem to get it to change both. An option to filter additional names would be great.

**Comment by EndlessEden** [comment]
I agree with this. Often nicknames and shortened variations of DN were used... far too often that i have to choose litterally between seeing full-firstname DN or reading 10,000 shortened DN first names.
A option to include nicknames would be extremely helpful.

**Comment by Hansondpaul** [comment]
Personal information has been edited for security

I agree. This needs to be added. I have been having this as an issue myself. Presuming my deadname is Jackson (it isn't), I would love the ability to replace both Jackson and Jack, and perhaps even Jak with my chosen name.

**Comment by Apyrl-lillie** [comment]
Also although it not as common, having the ability to change the first letter of your middle name would be another used for it. Most of the time, places will not print the full middle name but rather would put the first letter of the name followed by a period.

**Comment by WillHayCode** [comment]
Great suggestions y'all! You can expect to see nicknames and such in the next update, as well as middle names to first letter + period.
