### ISSUE TITLE
Suggesting a Feature; Momentary Disable Option?

### ISSUE THREAD

**Issue by celephine** [WillHayCode/Deadname-Remover#66]
So I love this extension! I find it super useful and its been a huge help dealing with dysphoria when I do school work, but an issue I have because of this is printing. When I go to print a document with my deadname, the captured page retains my real name and not my deadname (which is great, but for school it is an issue). I'd like to suggest a disable feature? Where clicking on the chrome extension has a choice like "Disable for ____ time" or "Disable for this page."

Please consider!

**Comment by WillHayCode** [comment]
This has been added in the latest update (1.2)
