### ISSUE TITLE
Quickly disable and change icon option

### ISSUE THREAD

**Issue by Vannie-codes** [WillHayCode/Deadname-Remover#69]
I love this extension so much it helped me a lot. It would be great if the extension had a quick disable option, like with a keyboard shortcut or something similar for when someone who you are not out to comes into your room. It would also be great if then the icon changed into something other than the trans flag.

**Comment by WillHayCode** [comment]
The newest update (1.2) adds a way to easily disable the extension. I'm looking into adding an incognito mode, thank you for the suggestion
