### ISSUE TITLE
MutationObserver doesn't consistently fire on Facebook

### ISSUE THREAD

**Issue by WillHayCode** [WillHayCode/Deadname-Remover#76]
For some reason, when I visit a page on Facebook the replacement rarely works since merging #72 

If I load the extension with the page already opens it does a partial replacement (first names only), and if a Facebook page is opened while the extension is already loaded it won't work at all.

**Comment by WillHayCode** [comment]
Further investigation has shown that the MutationObserver event _never_ fires on Facebook. Curious.

**Comment by WillHayCode** [comment]
Further investigation:

- A MutationObserver will fire if instantiated from within the console

- `Use of Mutation Events is deprecated. Use MutationObserver instead.` is a console warning on all Facebook pages.

**Comment by Gusted** [comment]
Side-Note: https://duckduckgo.com also shows some weird behavior. It seems like the text nodes don't even have a ParentNode to update It's child on 🤷🏽‍♀️. Also another issue fixed for duckduck.go by #77

**Comment by Gusted** [comment]
Been debugging for a hour by now I tried to even switch to a different MutationObserver Logic, but Facebook IDK it's just not getting it but reloading the extension just works. Even with #77 that should wait until the DOM is ready is not doing it for Facebook. I'm scratching my head a lot, btw when I tried to search for some similar code I came across [this add-on](https://github.com/Woundorf/foxreplace/) That works with the option `Replace on page load` but than Firefox changes it back unfortunate but it's noticeable it's been replaced.

**Comment by WillHayCode** [comment]
I've continued looking into this to very little luck, however I did notice that [Deadname-B-Gon](https://gitlab.com/jane314/deadname-b-gon) (an alternative plugin for the same purpose) uses mutation observers and did not appear to have the same issue. The code is interesting and well put together - however it is also licensed under Creative Commons 4.0 BY-NC-SA, which Creative Commons [advises against](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

I've contacted the author of Deadname-B-Gon proposing that we both relicense under GPLv3, however if that doesn't pan out I would be open to relicensing this to CC 4.0 BY-NC-SA.

**Comment by WillHayCode** [comment]
The current plan is to update the plugin on all platforms as soon as the MutationObserver implementation works across the board

**Comment by Gusted** [comment]
Hi @WillHayCode!

Thanks for pointing out the extension!
It seems at first it was similar execution and replacement.
But than I saw [this code](https://gitlab.com/jane314/deadname-b-gon/-/blob/master/main.js#L95).
And than it hit me, some elements have children already in it(pre-compiled in javascript) and are than inserted into the DOM. However my implementation only cares about the node that was inserted and not about childrenNodes(which can contain the actual text nodes). I will make a PR to fix this issue with some other changes(I think tree walker would be nice to be used however I'm scared for the possible performance issues).

Regards,
Gusted

**Comment by Gusted** [comment]
@WillHayCode 

Their you go #87
