### ISSUE TITLE
Extension makes Twitter really buggy

### ISSUE THREAD

**Issue by TerraKnight27** [WillHayCode/Deadname-Remover#78]
(This is on Firefox, without the GoodTwitter extension or anything similar to it)

The account switching menu (found on the bottom-left of the page) has trouble loading. Opening tweets/threads is also buggy; the replies don't appear until you slightly scroll through the page (which rarely makes them impossible to view), and if the tweet is a reply to something you are unable to fully scroll up through the thread.

**Comment by WillHayCode** [comment]
Thanks for the report! The next update (which is ready to go and should be on Firefox within the next few days) should fix this.
