### ISSUE TITLE
[Bug] The script repeating when a name is using a deadname

### ISSUE THREAD

**Issue by Call-Me-Apro** [WillHayCode/Deadname-Remover#9]
If you put the same name as your deadname and add something to the end (ex. name > name2) the script repeats and starts adding more and more of the suffixes. (resulting in ex. name222222222222222222222222222222...)

I feel like this is a serious issue as some languages have gendered surnames.

**Comment by WillHayCode** [comment]
Thanks for pointing this out! This should be an easy enough fix for the next update

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
