### ISSUE TITLE
Suggestion - when typing, only change after a space has been hit after a full word

### ISSUE THREAD

**Issue by dravenaddams** [WillHayCode/Deadname-Remover#90]
I have a couple of usernames that still include my deadname, especially in the format of [deadname]123 or other random numbers or letters. However, with the Deadname Remover on, I have to manually turn it off and on again sometimes when I type it in, like when sharing the username on Facebook Messenger, because it keeps changing the deadname into my real name before i type in the full thing, and puts the remaining characters in front of the whole message, so it looks like this:
231Message message Real Name
and it's frankly kind of annoying. I do appreciate that it changes it at all, but could it be possible to do so that it changes it only after a space or an enter has been hit? Thanks

**Comment by WillHayCode** [comment]
This should be resolved in the newest version (1.2)
