### ISSUE TITLE
Make Tampermonkey/Greasemonkey version

### ISSUE THREAD

**Issue by WillHayCode** [WillHayCode/Deadname-Remover#95]
There's been repeated reports of the plugin being blocked on school computers. Some of these are just a blanket ban on all extensions, but some are unfortunately targeted bans on LGBT+ related extensions. Luckily, I've also had it reported that in the latter case they **were** able to install the Tampermonkey extension. It shouldn't be too difficult to convert the plugin to a Tampermonkey/Greasemonkey script and add it as a build step.

**Comment by Gusted** [comment]
@WillHayCode 
Well, blocking LGBT+ related 😡. I'm going to have a look with the UMD output of webpack and get a user.js script working.
Oh yeah, any idea where the new Webpack Files are? I can't build anything atm

**Comment by WillHayCode** [comment]
@Gusted  - I had an error in my global git ignore and so they didn't commit, they should be present now

**Comment by Diyamund** [comment]
I'm thinking maybe they could make a seperate version that just replaces words so that transgender people could use it.
