### ISSUE TITLE
Two deadnames?

### ISSUE THREAD

**Issue by IntraVations** [WillHayCode/Deadname-Remover#99]
So, I saw this extension and it's great and perfect so far! so far, the big issue I'm running into though is that I go by two different names. One is my real name, and one is a shortened version of my name. Is there any way to change the extension so that you can put in more than one name? Thanks.

**Comment by Gurlyish** [comment]
I just made the exact same post without reading that there were more

**Comment by PiperTheFenic** [comment]
welp i just made a redundant post

**Comment by theratsimon** [comment]
i think if u type the shortened version of your deadname as ''middle name'' it should work
